version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    tty: true
    stdin_open: true
    ports:
      - 8080:8080
    volumes:
      - .:/go/src
